bootstrap.servers=localhost:9092
acks=all
retries=10
linger.ms=0
batch.size=16384
compression.type=none
enable.idempotence=false
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer
