server:
  port: 8080  # Tomcat default port

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092

    topic: message-topic
    superhero-topic: superhero-topic

app:
  kafka:
    market-rolling-topic: market.rolling.1h
  binance:
    ws-base-url: wss://stream.binance.com:9443/ws
    stream-name: '!ticker_1h@arr'
    reconnect-delay: 5s
