spring.application.name=user-service
server.port=8083
camunda.client.mode=saas
camunda.client.auth.client-id=X-hSIF0ujCIp3yB5KJZE-S6ocjPH4wwR
camunda.client.auth.client-secret=MmcXSVT0MllYQoiuEYeky6V92LxS~vo7vuSk8CdOV.-jhzVpnhUwhR6.HeqEbmql
camunda.client.cluster-id=70966460-4199-4643-a14f-64b0913ba8b7
camunda.client.region=lhr-1

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cryptoflow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cryptoflow}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cryptoflow}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false
user.confirmation.base-url=${USER_CONFIRMATION_BASE_URL:http://localhost:8083}
