bootstrap.servers=localhost:9092
group.id=test
auto.offset.reset=earliest
enable.auto.commit=true
max.poll.records=250
max.poll.interval.ms=300000
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
